try:
    a = 1/0

except:
    print('Um erro inesperado ocorreu.')
